Dubutoto/StockRadar

- logs/app.log
- src/main/java/org/example/stockradar/config/SecurityConfig.java
- src/main/java/org/example/stockradar/feature/auth/controller/AuthController.java
- src/main/java/org/example/stockradar/feature/auth/controller/ViewController.java
- src/main/java/org/example/stockradar/feature/auth/entity/Member.java
- src/main/java/org/example/stockradar/feature/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/org/example/stockradar/feature/auth/jwt/JwtTokenProvider.java
- src/main/java/org/example/stockradar/feature/auth/jwt/RefreshTokenRedisService.java
- src/main/java/org/example/stockradar/feature/auth/service/MemberService.java
- src/main/resources/application.yml
- src/main/resources/templates/login.html
- src/main/resources/templates/main.html
- src/main/resources/templates/signup.html
- src/main/resources/templates/test.html
> [FEAT] 로그인/회원가입 1차 구현

- logs/app.log
- src/main/java/org/example/stockradar/feature/CustomerInquiry/controller/CustomerInquiryController.java
- src/main/java/org/example/stockradar/feature/CustomerInquiry/entity/CustomerInquiry.java
- src/main/java/org/example/stockradar/feature/CustomerInquiry/service/CustomerInquiryService.java
- src/main/java/org/example/stockradar/global/exception/ErrorCode.java
- src/main/java/org/example/stockradar/global/exception/specific/CustomerInquiryException.java
- src/test/java/org/example/stockradar/CustomerInquiry/CustomerInquiryControllerTest.java
- src/test/java/org/example/stockradar/CustomerInquiry/CustomerInquiryServiceTest.java
> feat:고객문의 요청 구현(#32) 

- src/main/java/org/example/stockradar/feature/CustomerInquiry/controller/CustomerInquiryController.java
- src/main/java/org/example/stockradar/feature/CustomerInquiry/dto/CustomerInquiryResponseDto.java
- src/main/java/org/example/stockradar/feature/CustomerInquiry/dto/CustomerInquiryUserRequestDto.java
- src/main/java/org/example/stockradar/feature/CustomerInquiry/service/CustomerInquiryService.java
- src/main/java/org/example/stockradar/feature/customerInquiryprocessing/dto/CustomerInquiryProcessingRequestDto.java
- src/main/resources/static/js/customerInquiry/customerInquiry.js
- src/main/resources/templates/customerInquiry/customerInquiry.html
- src/test/java/org/example/stockradar/CustomerInquiry/CustomerInquiryControllerTwoTest.java
> feat: 고객문의 작성 4차 구현 완료(#43)

- build.gradle
- src/main/java/org/example/stockradar/config/SecurityConfig.java
- src/main/java/org/example/stockradar/feature/auth/controller/AuthController.java
- src/main/java/org/example/stockradar/feature/auth/controller/PasswordController.java
- src/main/java/org/example/stockradar/feature/auth/controller/ViewController.java
- src/main/java/org/example/stockradar/feature/auth/repository/MemberRepository.java
- src/main/java/org/example/stockradar/feature/auth/service/SmtpMailService.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/main/resources/templates/auth/idInquiry.html
- src/main/resources/templates/auth/resetPwForm.html
🛰️ Issue Number
#55 
🪐 작업 내용
아이디찾기,비밀번호 재설정 구현 완료
SMTP 관련 빌드, 설정 추가
Redis 에서 유효 토큰
비밀번호 재설정시 암호화
> feat: 아이디찾기,비밀번호 찾기 구현 완료(#55)

- build.gradle
- src/main/java/org/example/stockradar/feature/test/testController.java
- src/main/resources/application.yml
- src/main/resources/templates/product/gpu/rtx3050.html
> chore: s3 cdn 세팅 완료(#74)

- src/main/java/org/example/stockradar/config/SecurityConfig.java
- src/main/java/org/example/stockradar/feature/product/controller/ProductCategoryController.java
- src/main/resources/templates/layout.html
> chore: 시큐리티 설정 및 layout 변경 세팅 완료 (#80)

- src/main/java/org/example/stockradar/feature/auth/controller/AuthController.java
- src/main/java/org/example/stockradar/feature/auth/controller/ViewController.java
- src/main/resources/application-local.yml
🛰️ Issue Number
#85
🪐 작업 내용
맵핑 에러 해결& 테스트 까지 완료
📚 Reference
ddl: update, MYSQL password 확인
> bugfix: 맵핑 에러 해결& 테스트 까지 완료

- src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
- src/main/java/org/example/stockradar/feature/crawl/service/ProductStockService.java
- src/main/java/org/example/stockradar/feature/product/controller/ProductCategoryController.java
- src/main/java/org/example/stockradar/feature/product/dto/ProductResponseDto.java
- src/main/java/org/example/stockradar/feature/product/rtx3050/controller/Rtx3050Controller.java
- src/main/java/org/example/stockradar/feature/product/rtx3050/repository/Rtx3050Repository.java
- src/main/java/org/example/stockradar/feature/product/rtx3050/service/Rtx3050Service.java
- src/main/java/org/example/stockradar/global/exception/ErrorCode.java
- src/main/java/org/example/stockradar/global/exception/specific/ProductException.java
- src/main/resources/static/assets/js/product/rxt3050.js
- src/main/resources/templates/product/gpu/rtx3050.html
> feat: rtx3050 조회 1차 구현(#93)

- src/test/java/org/example/stockradar/product/rxt3050/Rtx3050ControllerExceptionTest.java
95
조회 jmeter성능테스트
tdd를 이용한 예외처리 테스트
> test: rtx3050 조회 예외처리 테스트 완료(#95)

- src/main/java/org/example/stockradar/feature/crawl/entity/Product.java
- src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
- src/main/java/org/example/stockradar/feature/product/dto/ProductResponseDto.java
- src/main/java/org/example/stockradar/feature/product/rtx3050/controller/Rtx3050Controller.java
- src/main/java/org/example/stockradar/feature/product/service/ProductALLServiceWithCache.java
> refactor : rex3050 시나리오3 구현 완료 (#106)

- src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
- src/main/java/org/example/stockradar/feature/crawl/service/ProductStockService.java
- src/main/java/org/example/stockradar/feature/product/rtx3060Ti/controller/Rtx3060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
> feat: 3060,4060Ti 시나리오2번 구현 완료(#121)

- src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
- src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
- src/main/java/org/example/stockradar/feature/product/rtx3060Ti/controller/Rtx3060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx3060Ti/service/Rtx3060TiService.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiService.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiStockCacheService.java
- src/main/java/org/example/stockradar/global/exception/ErrorCode.java
> feat: 4060Ti 시나리오3 번 구현 완료(#123)

- src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
- src/main/java/org/example/stockradar/feature/product/dto/ProductStaticCacheDto.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheService.java
> feat: rtx4060Ti 시나리오 4번 구현완료

- src/main/java/org/example/stockradar/feature/product/dto/ProductCacheDto.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV2.java
> refactor: 시나리오4번 V2구현완료(#134)

- src/main/java/org/example/stockradar/config/JacksonConfig.java
- src/main/java/org/example/stockradar/config/ProductRedisConfig.java
- src/main/java/org/example/stockradar/feature/product/dto/ProductStaticCacheDto.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV2.java
> bugfix: Redis LocalDateTime 직렬화 버그수정 완료 (#136)

- src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV2.java
> refactor: 스캐줄러 코드 리펙토링 완료(#142)

- src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
- src/main/java/org/example/stockradar/feature/product/dto/ProductResponseDto.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiLikeService.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiLikeV2Service.java
> refactor: 제품 재고 쿼리 튜닝 완료(#146)

- src/main/java/org/example/stockradar/feature/crawl/repository/ProductRepository.java
- src/main/java/org/example/stockradar/feature/crawl/scheduler/ProductStockScheduler.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3.java
> refactor: 스케줄러 변경사항 제품 재고 페이지 쿼리 수정(#148)

- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
> refactor: 4060Ti 조회비동기 처리 구현 완료(#155)

- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
- src/main/resources/application.yml
> bugfix: 비동기 처리 버그픽스 구현 완료(#158)

- src/main/java/org/example/stockradar/StockradarApplication.java
- src/main/java/org/example/stockradar/config/SecurityConfig.java
#156 
- sercurityConfig 수정
- 서버 주소 수정
> chore: sercurityConfig 수정

- src/main/java/org/example/stockradar/feature/auth/service/RedisSmtpService.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
- src/main/resources/application-local.yml
- src/main/resources/templates/customerInquiry/customerInquiry.html
167
레디스가 종료됬을때 smtp를 이용해 메일을 보냄
> feat: redis 고장 처리 구현 완료(#167)

- src/main/java/org/example/stockradar/feature/CustomerInquiry/controller/CustomerInquiryController.java
- src/main/java/org/example/stockradar/feature/auth/service/RedisSmtpService.java
- src/main/java/org/example/stockradar/feature/customerInquiryprocessing/controller/CustomerInquiryProcessingController.java
- src/main/java/org/example/stockradar/feature/customerInquiryprocessing/service/CustomerInquiryProcessingService.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/controller/Rtx4060Ticontroller.java
- src/main/java/org/example/stockradar/feature/product/rtx4060Ti/service/Rtx4060TiAllCacheServiceV3CompletableFuture.java
- src/main/java/org/example/stockradar/global/exception/ErrorCode.java
- src/main/resources/static/assets/js/customerInquiry/customerInquiry.js
- src/main/resources/static/assets/js/product/rxt4060Ti.js
> refactor:재고 페이지,고객문의,고객문의처리 수정완료(#177)

- src/main/resources/templates/main.html
> refactor: 메인 배너 수정(#182)

- src/main/resources/templates/layout.html
> refactor: rayout.html 수정완료(#200)
